/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 8e3f1a042f87eb877dbcf7fd6f38c5d4)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAssistant" | "AssistantDirectory" | "ExecutionAgent";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    MEMORY_VECTORIZE: Vectorize;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    AssistantDirectory: DurableObjectNamespace<import("./src/server").AssistantDirectory>;
    MyAssistant: DurableObjectNamespace<import("./src/server").MyAssistant>;
    ExecutionAgent: DurableObjectNamespace<import("./src/server").ExecutionAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET">
  > {}
}
